### ISSUE TITLE
data type question

### ISSUE THREAD

**Issue by kotaxyz** [jiawei-ren/diffmimic#1]
Thanks for the awesome work , i have a question does this method works with mocap data only or does it work with video data too

**Comment by jiawei-ren** [comment]
Thank you for your interest in this work! It works with mocap data only, but for videos, we can first estimate the motions from the videos and then mimic them. We have included examples for [AIST++](https://google.github.io/aistplusplus_dataset/factsfigures.html), where dancing motions are estimated from multi-view videos in [SMPL](https://smpl.is.tue.mpg.de/) format.
<img src="https://user-images.githubusercontent.com/72253125/230646697-f637e858-c5b5-40be-a070-d5397c7dba9e.gif" width="400"/>
We show how to preprocess the SMPL sequences [here](https://github.com/jiawei-ren/diffmimic/blob/main/data/tools/aist_converter.py) and example configs [here](https://github.com/jiawei-ren/diffmimic/tree/main/configs/AIST).
