### ISSUE TITLE
Start my own training

### ISSUE THREAD

**Issue by yinkangning0124** [jiawei-ren/diffmimic#4]
Hi jiawei,
    Thanks for your awesome work. I want to know how to train the model with my own amass dataset, can you give me a detailed README on how to start training?
    Another question is that is there any pre-trained model?
Best,
Kangning

**Comment by jiawei-ren** [comment]
Hi Kangning,

You can try the converter script [here](https://github.com/jiawei-ren/diffmimic/blob/main/data/tools/amass_converter.py), it works with the official AMASS dataset. 

The request for pre-trained models is noted, I will upload them when I get the time. But generally training a policy should take less than two hours.
